version: "3"
services:
  # torrent client to download media from the internet
  qbittorrent:
    environment:
      - PUID={userId}
      - PGID={userGroupId}
    volumes:
      - {mediaFolderPath}:/media
  # media server to distribute downloaded media on the local network
  plex:
    environment:
      - PUID={userId}
      - PGID={userGroupId}
    volumes:
      - {mediaFolderPath}:/media
      - {configFolderPath}:/config
  home-media-app:
    volumes:
      - {mediaFolderPath}:/shows
      - {configFolderPath}:/data
  plex-listener:
    volumes:
      - {mediaLogsFolderPath}:/plex/logs