version: "3"
services:
  # torrent client to download media from the internet
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: always
  # media server to distribute downloaded media on the local network
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - VERSION=docker
    # Plex doesn't really run well behind NAT, so it is advised to use "host" network_mode
    network_mode: host
    restart: always
  # mobile-friendly web ui for torrent service
  torrent-ui:
    image: gorolykmaxim/torrent-ui
    container_name: torrent-ui
    environment:
      - SERVER_PORT=8080
      - SPRING_MVC_VIEW_PREFIX=/WEB-INF/view/
      - SPRING_MVC_VIEW_SUFFIX=.jsp
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/home-media-app
      - SPRING_DATASOURCE_USERNAME=homemediaapp
      - SPRING_DATASOURCE_PASSWORD=homemediaapp
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TORRENT_UI_QBITTORRENT_BASE_URI=http://qbittorrent:8080
      - TORRENT_UI_QBITTORRENT_USERNAME=admin
      - TORRENT_UI_QBITTORRENT_PASSWORD=adminadmin
      - TORRENT_UI_COMMON_DURATION_FORMAT=H:mm:ss
      - TORRENT_UI_COMMON_DOWNLOAD_SPEED_FORMAT=%s / %s
      - TORRENT_UI_TORRENT_SORT=progress
      - TORRENT_UI_TORRENT_REVERSE=true
      - TORRENT_UI_TORRENT_DEFAULT_DOWNLOAD_FOLDER=/media/
      - TORRENT_UI_TORRENT_REFRESH_INTERVAL=1000
    ports:
      - 8081:8080
    restart: always
#  # Plex logs listener, that notifies home-media-app about different events in Plex
#  plex-listener:
#    image: gorolykmaxim/plex-listener:1.1.5
#    container_name: plex-listener
#    environment:
#      - MESSAGE_REGEXP=.*\'(.*)\'( -)? got played.*
#      - HOME_MEDIA_APP_URL=http://home-media-app:8080/api/v1/episode/view
#      - ATTRIBUTE_NAME=episodeName
#    depends_on:
#      - plex
#    restart: always
#  # Single page web-ui
#  web-ui:
#    image: gorolykmaxim/web-ui:1.0.1
#    container_name: web-ui
#    ports:
#      - 80:80
#    restart: always
