version: "3"
services:
  # torrent client to download media from the internet
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: always
  # media server to distribute downloaded media on the local network
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - VERSION=docker
    # Plex doesn't really run well behind NAT, so it is advised to use "host" network_mode
    network_mode: host
    restart: always
  # Web UI of the whole media server
  web-ui:
    depends_on:
      - qbittorrent
      - plex
    image: nginx:1.15.9-alpine
    container_name: web-ui
    ports:
      - 80:80
    volumes:
      - ./web-ui/nginx.conf:/etc/nginx/nginx.conf
      - ./web-ui/app:/web-ui
    restart: always