version: "3"
services:
  # torrent client to download media from the internet
  qbittorrent:
    environment:
      - PUID={userId}
      - PGID={userGroupId}
    volumes:
      - {mediaFolderPath}:/media
  # media server to distribute downloaded media on the local network
  plex:
    environment:
      - PUID={userId}
      - PGID={userGroupId}
    volumes:
      - {mediaFolderPath}:/media
      - {configFolderPath}:/config
  # collector and analyzer of plex logs, that publishes some of them to the message queue
  plex-log-collector:
    volumes:
      - {configFolderPath}:/data
  # mobile-friendly web ui for torrent service
  torrent-ui:
    user: '{userId}:{userGroupId}'
    volumes:
      - {configFolderPath}:/data
  # service that tells you what videos you have watched
  videos-watched:
    user: '{userId}:{userGroupId}'
    volumes:
      - {configFolderPath}:/data
  # service that searches images based on the specified search query
  thumbnail-search:
    user: '{userId}:{userGroupId}'
    volumes:
      - {configFolderPath}:/data
