version: "3"
services:
  # torrent client to download media from the internet
  qbittorrent:
    image: linuxserver/qbittorrent:4.3.0202003011834-6876-b519eceubuntu18.04.1-ls16
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ${MEDIA_FOLDER_PATH}:/media
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: always
  # media server to distribute downloaded media on the local network
  plex:
    image: linuxserver/plex:1.18.7.2457-77cb9455c-ls80
    container_name: plex
    environment:
      - VERSION=docker
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ${MEDIA_FOLDER_PATH}:/media
      - ${ROOT_FOLDER_PATH}:/config
    restart: always
