version: "3"
services:
  # torrent client to download media from the internet
  qbittorrent:
    image: linuxserver/qbittorrent:4.3.0202003011834-6876-b519eceubuntu18.04.1-ls16
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ${MEDIA_FOLDER_PATH}:/media
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: always
  # media server to distribute downloaded media on the local network
  plex:
    image: linuxserver/plex:1.18.7.2457-77cb9455c-ls80
    container_name: plex
    environment:
      - VERSION=docker
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ${MEDIA_FOLDER_PATH}:/media
      - ${ROOT_FOLDER_PATH}:/config
    restart: always
  # mobile-friendly web ui for torrent service
  torrent-ui:
    image: gorolykmaxim/torrent-ui:1.1.1
    container_name: torrent-ui
    environment:
      - SERVER_PORT=8080
      - SPRING_MVC_VIEW_PREFIX=/WEB-INF/view/
      - SPRING_MVC_VIEW_SUFFIX=.jsp
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/torrent-ui
      - SPRING_DATASOURCE_USERNAME=torrentui
      - SPRING_DATASOURCE_PASSWORD=torrentui
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TORRENT_UI_QBITTORRENT_BASE_URI=http://qbittorrent:8080
      - TORRENT_UI_QBITTORRENT_USERNAME=admin
      - TORRENT_UI_QBITTORRENT_PASSWORD=adminadmin
      - TORRENT_UI_COMMON_DURATION_FORMAT=H:mm:ss
      - TORRENT_UI_COMMON_DOWNLOAD_SPEED_FORMAT=%s / %s
      - TORRENT_UI_TORRENT_SORT=progress
      - TORRENT_UI_TORRENT_REVERSE=true
      - TORRENT_UI_TORRENT_DEFAULT_DOWNLOAD_FOLDER=/media/
      - TORRENT_UI_TORRENT_REFRESH_INTERVAL=1000
    user: '${USER_ID}:${GROUP_ID}'
    volumes:
      - ${ROOT_FOLDER_PATH}:/data
    ports:
      - 8081:8080
    restart: always
  # collector and analyzer of plex logs, that publishes some of them to the message queue
  plex-log-collector:
    image: gorolykmaxim/plex-log-collector:1.0.2
    container_name: plex-log-collector
    volumes:
      - ${ROOT_FOLDER_PATH}:/data
    depends_on:
      - kafka
    restart: always
  # consumer-based message queue, kafka
  kafka:
    image: spotify/kafka
    container_name: kafka
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
    ports:
      - 2181:2181
      - 9092:9092
    restart: always
  # service that shows history of videos being watched through plex
  videos-watched:
    image: gorolykmaxim/videos-watched:1.0.3
    container_name: videos-watched
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/videos-watched
      - SPRING_DATASOURCE_USERNAME=videoswatched
      - SPRING_DATASOURCE_PASSWORD=videoswatched
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP_ID=videos-watched
      - SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
      - VIDEOS_WATCHED_LIBRARY_ROOT=/media
      - VIDEOS_WATCHED_DURATION_FORMAT=m 'minutes' s 'seconds'
    user: '${USER_ID}:${GROUP_ID}'
    volumes:
    - ${ROOT_FOLDER_PATH}:/data
    - ${MEDIA_FOLDER_PATH}:/media
    ports:
    - 8082:8080
    restart: always
  # service that provides links to all services in the media server, that have web UI
  home-page:
    image: gorolykmaxim/home-page:1.1.1
    container_name: home-page
    ports:
    - 80:80
    restart: always
