--liquibase formatted sql

--changeset maxim:1
CREATE TABLE VIDEO(
    VIDEO_ID BIGINT PRIMARY KEY,
    NAME VARCHAR,
    TIME_PLAYED BIGINT,
    TOTAL_TIME BIGINT,
    RELATIVE_PATH VARCHAR,
    LAST_PLAY_DATE TIMESTAMP NOT NULL
);

CREATE TABLE NOTIFICATION(
    NOTIFICATION_ID UUID PRIMARY KEY,
    CONTENT VARCHAR
);
--rollback DROP TABLE VIDEO; DROP TABLE NOTIFICATION;